export const PREFIX = "@@success/";

export const ASYNC_SUCCESS_INIT = `${PREFIX}ASYNC_SUCCESS_INIT`;
export const INITIALIZE_SUCCESS_INIT = `${PREFIX}INITIALIZE_SUCCESS_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_SUCCESS_RATE_SUCCESS = `${PREFIX}GET_SUCCESS_RATE_SUCCESS`;
