export const PREFIX = "@@weather/";

export const ASYNC_WEATHER_INIT = `${PREFIX}ASYNC_WEATHER_INIT`;
export const INITIALIZE_WEATHER_INIT = `${PREFIX}INITIALIZE_WEATHER_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_WEATHER_SUCCESS = `${PREFIX}GET_WEATHER_SUCCESS`;
